import {WindowWithDataLayer} from './../types/index.d'
var window:WindowWithDataLayer;

export default function Head() {
 
  return (
    <>
      <title>Wunderber Kenya - Tours and Safris</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* <!-- Google tag (gtag.js) --> */} 
      {/* <script async src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}`}></script> */}
      {/* <script>
      window.dataLayer = window.dataLayer || [];
        

        function gtag(){
          window.dataLayer.push(arguments)
        }
        gtag(`js`, new Date());

        gtag(`config`, `${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}`);
      </script>  */}
       

    </>
  )
}
