on:
  push:
    branches: dev

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🔨 pkg installation and build
        run: |
          npm install -f
          npm run build
        
      - name: 📂 Sync FrontEnd files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          exclude: |
           **/.git*
           **/.git*/**
           **/node_modules/**
           *lock.json
          server-dir: ./dev2.wunderber.com/
          dangerous-clean-slate: true

      
