on:
  push:
    branches: dev

name: 🚀 Deploy dev-site on push on the dev branch
jobs:
  web-deploy:
    name: 🎉 Deploy1
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: 🔨 pkg installation and build
        run: |
          npm install
          npm run build

        env:
          DATABASE_URL: ${{secrets.DB_URL}}
        
      - name: 📂 Sync FrontEnd files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          exclude: |
           **/.vscode/**
           **/.git*
           **/.git*/**
           **/node_modules/**
           *lock.json
          server-dir: ./dev2.wunderber.com/
          # dangerous-clean-slate: true

      
      - name: Set up SSH connection to server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy app using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{secrets.SSH_PORT}}
          script: |
            pwd
            source /home/mwerothe/nodevenv/dev2.wunderber.com/16/bin/activate && cd /home/mwerothe/dev2.wunderber.com
            npm i
            npm run build
            cloudlinux-selector restart  --json --interpreter nodejs --app-root /home/mwerothe/dev2.wunderber.com
