name: Deploy to cPanel
on:
  push:
    branches: [ stag ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER_WUNDERBER }}
        password: ${{ secrets.PWD_WUNDERBER}}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/myusername/myapp
          git pull origin main
          npm install
          npm run build
          pm2 restart myapp
